---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeb5645-test-flask-deployment
  labels:
    username: jeb5645
    env: test
    app: jeb5645-test-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      username: jeb5645
      env: test
      app: jeb5645-test-flask
  template:
    metadata:
      labels:
        username: jeb5645
        env: test
        app: jeb5645-test-flask
    spec:
      containers:
        - name: jeb5645-test-flask
          image: jordaneburton/gene_api.py:1.0
          env:
          - name: REDIS_HOST
            value: "jeb5645-test-redis-service"
          volumeMounts:
          - name: jeb5645-test-data
            mountPath: "/data"
      volumes:
      - name: jeb5645-test-data
        persistentVolumeClaim:
          claimName: jeb5645-test-data
