---
version: "3"

services:
    redis-db:
        image: redis:7
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
        user: "1000:1000"
        command: redis-server
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - redis-db
        image: jordaneburton/gene_api.py:hw8
        ports:
            - 5000:5000
        environment:
            - REDIS_HOST=redis-db
        volumes:
            - ./config.yaml:/config.yaml
